// This file was automatically generated by https://github.com/kbinani/win/blob/generator/internal/cmd/gen/gen.go
// go run internal/cmd/gen/gen.go

// +build windows

package win

import (
	"unsafe"
)

const (
	INTERNET_PER_CONN_FLAGS               = 1
	INTERNET_PER_CONN_PROXY_SERVER        = 2
	INTERNET_PER_CONN_PROXY_BYPASS        = 3
	INTERNET_PER_CONN_AUTOCONFIG_URL      = 4
	INTERNET_PER_CONN_AUTODISCOVERY_FLAGS = 5
)

const (
	PROXY_TYPE_DIRECT         = 0x00000001 // direct to net
	PROXY_TYPE_PROXY          = 0x00000002 // via named proxy
	PROXY_TYPE_AUTO_PROXY_URL = 0x00000004 // autoproxy URL
	PROXY_TYPE_AUTO_DETECT    = 0x00000008 // use autoproxy detection

	INTERNET_OPTION_PER_CONNECTION_OPTION = 75
)

type INTERNET_PER_CONN_OPTIONA struct {
	DwOption DWORD
	Value    uint64
}

func (t *INTERNET_PER_CONN_OPTIONA) Value_dwValue() DWORD {
	//return (DWORD)(binary.LittleEndian.Uint32(t.Value[:]))
	return (DWORD)(uint32(t.Value))
}

func (t *INTERNET_PER_CONN_OPTIONA) Value_pszValue() unsafe.Pointer {
	return unsafe.Pointer(uintptr(t.Value))
}

//func (t *INTERNET_PER_CONN_OPTIONA) Value_pszValue() LPSTR {
//	return (LPSTR)(unsafe.Pointer(uintptr(t.Value)))
//return (LPSTR)(unsafe.Pointer(uintptr(binary.LittleEndian.Uint32(t.Value[:]))))
//}

//func (t *INTERNET_PER_CONN_OPTIONA)Value_ftValue() FILETIME {
//	return (FILETIME)(t.Value)
//}

type LPINTERNET_PER_CONN_OPTIONA *INTERNET_PER_CONN_OPTIONA

type INTERNET_PER_CONN_OPTION_LISTA struct {
	DwSize        DWORD
	PszConnection LPSTR
	DwOptionCount DWORD
	DwOptionError DWORD
	POptions      LPINTERNET_PER_CONN_OPTIONA
}

var (
	// Library
	winnetapi uintptr
	// Functions
	internetSetOptionA   uintptr
	internetQueryOptionA uintptr
)

type HINTERNET uintptr

func init() {
	// Library
	winnetapi = doLoadLibrary("wininet.dll")
	// Functions
	internetQueryOptionA = doGetProcAddress(winnetapi, "InternetQueryOptionA")
	internetSetOptionA = doGetProcAddress(winnetapi, "InternetSetOptionA")
}

func InternetSetOptionA(hInternet unsafe.Pointer,
	dwOption DWORD,
	lpBuffer unsafe.Pointer,
	dwBufferLength *uint32) bool {
	ret1 := syscall6(internetSetOptionA, 4,
		uintptr(hInternet),
		uintptr(dwOption),
		uintptr(lpBuffer),
		uintptr(unsafe.Pointer(dwBufferLength)),
		0,
		0)
	return ret1 != 0
}

func InternetQueryOptionA(hInternet unsafe.Pointer,
	dwOption DWORD,
	lpBuffer unsafe.Pointer,
	dwBufferLength *uint32) bool {
	ret1 := syscall6(internetQueryOptionA, 4,
		uintptr(hInternet),
		uintptr(dwOption),
		uintptr(lpBuffer),
		uintptr(unsafe.Pointer(dwBufferLength)),
		0,
		0)
	return ret1 != 0

}
